name: "Secure Pipeline Test -Dast-Zap"
on: ["push","pull_request"]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: OWASP ZAP
        uses: zaproxy/action-baseline@v0.4.0
        with:
           # Target URL
          target: "https://search1.cfappsecurity.com/"
          fail_action: false
          token: $
          issue_title: Security Tests
    
