name: "Secure Pipeline Test - Dependency Check"
on: ["push","pull_request"]
jobs:
    sca:
        runs-on: ubuntu-latest
        container:
            image: owasp/dependency-check
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Dependency Check
          run: dependency-check --format ALL --scan .
        - name: Archive Reports
          uses: actions/upload-artifact@v2
          with:
              name: dependency-check-reports
              path: |
                  ./dependency-check-report.html
     
